/*
Foundry
Copyright 2020 Carnegie Mellon University.
NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
Released under a MIT (SEI)-style license, please see license.txt or contact permission@sei.cmu.edu for full terms.
[DISTRIBUTION STATEMENT A] This material has been approved for public release and unlimited distribution.  Please see Copyright notice for non-US Government use and distribution.
Carnegie Mellon(R) and CERT(R) are registered in the U.S. Patent and Trademark Office by Carnegie Mellon University.
DM20-0194
*/

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Foundry.Communications.Data;

namespace Foundry.Communications.Data.PostgreSQL.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    partial class CommunicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("SourceId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.GroupTarget", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("TargetId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TargetId");

                    b.ToTable("GroupTargets");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime?>("Broadcast");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("GlobalId");

                    b.Property<int?>("GroupId");

                    b.Property<int>("Priority");

                    b.Property<string>("SourceId")
                        .IsRequired();

                    b.Property<string>("Subject");

                    b.Property<string>("TargetId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.MessageValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<int>("MessageId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageValue");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired();

                    b.Property<DateTime?>("Broadcast");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("GlobalId");

                    b.Property<int>("Priority");

                    b.Property<string>("SourceId")
                        .IsRequired();

                    b.Property<string>("Subject");

                    b.Property<string>("TargetId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.NotificationValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<int>("NotificationId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationValue");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Deleted");

                    b.Property<int?>("MessageId");

                    b.Property<int?>("NotificationId");

                    b.Property<DateTime?>("Read");

                    b.Property<string>("TargetId");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("TargetId");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Source", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LogoUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Target", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Group", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.GroupTarget", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Foundry.Communications.Data.Entities.Target", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Message", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Foundry.Communications.Data.Entities.Source", "Source")
                        .WithMany("Messages")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Foundry.Communications.Data.Entities.Target")
                        .WithMany("Messages")
                        .HasForeignKey("TargetId");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.MessageValue", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Message", "Message")
                        .WithMany("Values")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Notification", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Source", "Source")
                        .WithMany("Notifications")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Foundry.Communications.Data.Entities.Target")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetId");
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.NotificationValue", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Notification", "Notification")
                        .WithMany("Values")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Foundry.Communications.Data.Entities.Recipient", b =>
                {
                    b.HasOne("Foundry.Communications.Data.Entities.Message", "Message")
                        .WithMany("Recipients")
                        .HasForeignKey("MessageId");

                    b.HasOne("Foundry.Communications.Data.Entities.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId");

                    b.HasOne("Foundry.Communications.Data.Entities.Target", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId");
                });
#pragma warning restore 612, 618
        }
    }
}

